# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
      include:
      - master
      - develop
  paths:
    include:
    - Sources

pool:
  vmImage: ubuntu-latest

variables:
        buildConfiguration: 'Release'
        dotNetFramework: 'net6.0'
        dotNetVersion: '6.0.x'
        targetRuntime: 'linux-x64'


steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '-o ./binaries'
    zipAfterPublish: false

